"""Added GDL tables

Revision ID: ce68aa04d8a6
Revises: 7607db356dd5
Create Date: 2024-12-19 18:49:29.617958

"""

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = "ce68aa04d8a6"
down_revision = "7607db356dd5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "iso_country",
        sa.Column("iso_code", sa.String(), nullable=False),
        sa.Column("country_name", sa.String(), nullable=False),
        sa.Column("continent", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("iso_code"),
    )
    op.create_index(
        op.f("ix_iso_country_iso_code"), "iso_country", ["iso_code"], unique=False
    )
    op.create_table(
        "gdl_region",
        sa.Column("gdl_code", sa.String(), nullable=False),
        sa.Column("region_name", sa.String(), nullable=False),
        sa.Column("level", sa.String(), nullable=False),
        sa.Column("iso_code", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["iso_code"],
            ["iso_country.iso_code"],
        ),
        sa.PrimaryKeyConstraint("gdl_code"),
    )
    op.create_index(
        op.f("ix_gdl_region_gdl_code"), "gdl_region", ["gdl_code"], unique=False
    )
    op.create_table(
        "development",
        sa.Column("year", sa.SmallInteger(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("gdl_code", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gdl_code"],
            ["gdl_region.gdl_code"],
        ),
        sa.PrimaryKeyConstraint("year", "gdl_code"),
    )
    op.create_index(
        op.f("ix_development_gdl_code"), "development", ["gdl_code"], unique=False
    )
    op.create_index(op.f("ix_development_year"), "development", ["year"], unique=False)
    op.create_table(
        "education",
        sa.Column("year", sa.SmallInteger(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("gdl_code", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gdl_code"],
            ["gdl_region.gdl_code"],
        ),
        sa.PrimaryKeyConstraint("year", "gdl_code"),
    )
    op.create_index(
        op.f("ix_education_gdl_code"), "education", ["gdl_code"], unique=False
    )
    op.create_index(op.f("ix_education_year"), "education", ["year"], unique=False)
    op.create_table(
        "gdl_national",
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=False,
        ),
        sa.Column("gdl_code", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gdl_code"],
            ["gdl_region.gdl_code"],
        ),
        sa.PrimaryKeyConstraint("gdl_code"),
    )
    op.create_index(
        op.f("ix_gdl_national_gdl_code"), "gdl_national", ["gdl_code"], unique=False
    )
    op.create_table(
        "gdl_subnational",
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=False,
        ),
        sa.Column("gdl_code", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gdl_code"],
            ["gdl_region.gdl_code"],
        ),
        sa.PrimaryKeyConstraint("gdl_code"),
    )
    op.create_index(
        op.f("ix_gdl_subnational_gdl_code"),
        "gdl_subnational",
        ["gdl_code"],
        unique=False,
    )
    op.create_table(
        "healthcare",
        sa.Column("year", sa.SmallInteger(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("gdl_code", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gdl_code"],
            ["gdl_region.gdl_code"],
        ),
        sa.PrimaryKeyConstraint("year", "gdl_code"),
    )
    op.create_index(
        op.f("ix_healthcare_gdl_code"), "healthcare", ["gdl_code"], unique=False
    )
    op.create_index(op.f("ix_healthcare_year"), "healthcare", ["year"], unique=False)
    op.create_table(
        "income",
        sa.Column("year", sa.SmallInteger(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("gdl_code", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gdl_code"],
            ["gdl_region.gdl_code"],
        ),
        sa.PrimaryKeyConstraint("year", "gdl_code"),
    )
    op.create_index(op.f("ix_income_gdl_code"), "income", ["gdl_code"], unique=False)
    op.create_index(op.f("ix_income_year"), "income", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_income_year"), table_name="income")
    op.drop_index(op.f("ix_income_gdl_code"), table_name="income")
    op.drop_table("income")
    op.drop_index(op.f("ix_healthcare_year"), table_name="healthcare")
    op.drop_index(op.f("ix_healthcare_gdl_code"), table_name="healthcare")
    op.drop_table("healthcare")
    op.drop_index(op.f("ix_gdl_subnational_gdl_code"), table_name="gdl_subnational")
    op.drop_table("gdl_subnational")
    op.drop_index(op.f("ix_gdl_national_gdl_code"), table_name="gdl_national")
    op.drop_table("gdl_national")
    op.drop_index(op.f("ix_education_year"), table_name="education")
    op.drop_index(op.f("ix_education_gdl_code"), table_name="education")
    op.drop_table("education")
    op.drop_index(op.f("ix_development_year"), table_name="development")
    op.drop_index(op.f("ix_development_gdl_code"), table_name="development")
    op.drop_table("development")
    op.drop_index(op.f("ix_gdl_region_gdl_code"), table_name="gdl_region")
    op.drop_table("gdl_region")
    op.drop_index(op.f("ix_iso_country_iso_code"), table_name="iso_country")
    op.drop_table("iso_country")
    # ### end Alembic commands ###
