version: '3'
services:
  db:
    image: postgis/postgis:13-3.1-alpine
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data:rw
    env_file:
      - ./envs/.db.env

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - ./envs/.pgadmin.env
    ports:
      - 5000:80

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel debug
    volumes: 
      - ./data/redis:/data

  dataproc:
    image: ccgautopkg:0.1-dev
    build: ./ccgautopkg
    volumes:
      - ./data/dataproc:/data
    environment:
      - CCGAUTOPKG_CELERY_BROKER=redis://redis:6379
      - CCGAUTOPKG_CELERY_BACKEND=redis://redis:6379
    command: celery --app dataproc.tasks worker --loglevel=debug

  api:
    image: ccgautopkg:0.1-dev
    build: ./ccgautopkg
    volumes:
      - ./ccgautopkg:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - envs/.api.env
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload