version: '3'
services:
  db:
    image: postgis/postgis:13-3.1-alpine
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data:rw
    env_file:
      - ./envs/.db.env

  nginx:
    image: nginx:latest
    build: ./nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./data/packages:/www/data/packages

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel debug
    volumes: 
      - ./data/redis:/data

  dataproc:
    image: ccgautopkg:0.1-dev
    build: ./ccgautopkg
    volumes:
      - ./data/packages:/data/packages
      - ./data/tmp:/data/tmp
      - ./tests/data/packages:/usr/src/app/tests/data/packages
      - ./tests/data/tmp:/usr/src/app/tests/data/tmp
    env_file:
      - envs/.api_and_dataproc.env
    command: celery --app dataproc.tasks worker --loglevel=debug --concurrency=4

  api:
    image: ccgautopkg:0.1-dev
    build: ./ccgautopkg
    volumes:
      - ./data/packages:/data/packages
      - ./data/tmp:/data/tmp
      - ./tests/data/packages:/usr/src/app/tests/data/packages
      - ./tests/data/tmp:/usr/src/app/tests/data/tmp
    ports:
      - 8000:8000
    env_file:
      - envs/.api_and_dataproc.env
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload


  # These test-harness containers require API and Dataproc to be running
  # WARNING - THESE TESTS WILL WIPE THE CONFIGURED TEST HARNESS DB from anything in MODELS
  test-api:
    image: ccgautopkg:0.1-dev
    build: ./ccgautopkg
    volumes:
      - ./tests/data/packages:/usr/src/app/tests/data/packages
      - ./tests/data/tmp:/usr/src/app/tests/data/tmp
    env_file:
      - envs/.api_and_dataproc.env
    command: python3 -m unittest discover /usr/src/app/tests/api

  test-dataproc:
    image: ccgautopkg:0.1-dev
    build: ./ccgautopkg
    volumes:
      - ./tests/data/packages:/usr/src/app/tests/data/packages
      - ./tests/data/tmp:/usr/src/app/tests/data/tmp
    env_file:
      - envs/.api_and_dataproc.env
    command: python -m unittest discover /usr/src/app/tests/dataproc