version: '3'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel debug
    volumes: 
      - ./data/redis:/data

  dataproc:
    image: ccgautopkg:0.1-dev
    build: ./ccgautopkg
    volumes:
      - ./data/dataproc:/data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    command: celery --app dataproc.tasks worker --loglevel=debug

  api:
    image: ccgautopkg:0.1-dev
    build: ./ccgautopkg
    volumes:
      - ./ccgautopkg:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload