"""
Custom Dataproc exceptions
"""


class DataProcException(Exception):
    pass


class ConfigException(DataProcException):
    """Error with configuration"""


class FolderNotFoundException(DataProcException):
    """A Foler could not be found on the backend"""


class PackageNotFoundException(DataProcException):
    """Package with a given name does not exist on the StorageBackend"""


class DatasetNotFoundException(DataProcException):
    """Dataset with within a package does not exist on the StorageBackend"""


class S3Exception(DataProcException):
    """Wrapper for exceptions generated by S3 filesystem"""
